-- Insertar tipo de división geográfica ADM1 para AFGANISTÁN: Provincia
INSERT INTO `t075t_division_types` (
    `code`, `id_country`, `id_level_type`, `name_spanish`, `name_english`, 
    `name_iso`, `name_original`, `name_transcribed`, `status`, 
    `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES (
    'provincia_af', 1, 8, 'Provincia', 'Province', 
    'Velāyat', 'ولایت', 'Provincia', 1, NOW(6), NOW(6), 1, 1
);

-- Insertar las divisiones ADM1 de AFGANISTÁN (Provincias)
INSERT INTO `t076t_states` (
    `geo_id`, `id_country`, `code`, `code_dane`, `code_dian`, `code_iso_numeric`, 
    `code_iso_alpha2`, `code_iso_alpha3`, `phone_code`, `id_division_type`, 
    `name_spanish`, `name_english`, `name_iso`, `name_original`, `name_transcribed`, 
    `status`, `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES 
(1121143, 1, 'AF-ZAB', NULL, NULL, '0', 'AF-ZAB', 'AF-ZAB', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Zābul', 'Zabul', 'Zābul', 'Wilāyat-e Zābul', 'Zābul', 1, NOW(6), NOW(6), 1, 1),
(1121863, 1, 'AF-WAR', NULL, NULL, '0', 'AF-WAR', 'AF-WAR', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Wardak', 'Wardak', 'Wardak', 'Wardak', 'Wardak', 1, NOW(6), NOW(6), 1, 1),
(1123230, 1, 'AF-TAK', NULL, NULL, '0', 'AF-TAK', 'AF-TAK', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Takhār', 'Takhar', 'Takhār', 'Wilāyat-e Takhār', 'Takhār', 1, NOW(6), NOW(6), 1, 1),
(1127106, 1, 'AF-SAR', NULL, NULL, '0', 'AF-SAR', 'AF-SAR', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Sar-e Pul', 'Sar-e Pul', 'Sar-e Pul', 'Sar-e Pul', 'Sar-e Pul', 1, NOW(6), NOW(6), 1, 1),
(1127766, 1, 'AF-SAM', NULL, NULL, '0', 'AF-SAM', 'AF-SAM', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Samangān', 'Samangan', 'Samangān', 'Samangān', 'Samangān', 1, NOW(6), NOW(6), 1, 1),
(1131054, 1, 'AF-PAR', NULL, NULL, '0', 'AF-PAR', 'AF-PAR', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Parwān', 'Parwan', 'Parwān', 'Parwān', 'Parwān', 1, NOW(6), NOW(6), 1, 1),
(1131256, 1, 'AF-PKA', NULL, NULL, '0', 'AF-PKA', 'AF-PKA', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Paktīkā', 'Paktika', 'Paktīkā', 'Wilāyat-e Paktīkā', 'Paktīkā', 1, NOW(6), NOW(6), 1, 1),
(1131257, 1, 'AF-PIA', NULL, NULL, '0', 'AF-PIA', 'AF-PIA', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Paktiyā', 'Paktia', 'Paktiyā', 'Wilāyat-e Paktiyā', 'Paktiyā', 1, NOW(6), NOW(6), 1, 1),
(1131461, 1, 'AF-URU', NULL, NULL, '0', 'AF-URU', 'AF-URU', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Uruzgān', 'Uruzgan', 'Uruzgān', 'Uruzgān', 'Uruzgān', 1, NOW(6), NOW(6), 1, 1),
(1131821, 1, 'AF-NIM', NULL, NULL, '0', 'AF-NIM', 'AF-NIM', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Nīmrōz', 'Nimroz', 'Nīmrōz', 'Wilāyat-e Nīmrōz', 'Nīmrōz', 1, NOW(6), NOW(6), 1, 1),
(1132366, 1, 'AF-NAN', NULL, NULL, '0', 'AF-NAN', 'AF-NAN', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Nangarhār', 'Nangarhar', 'Nangarhār', 'Nangarhār', 'Nangarhār', 1, NOW(6), NOW(6), 1, 1),
(1134561, 1, 'AF-LOG', NULL, NULL, '0', 'AF-LOG', 'AF-LOG', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Lōgar', 'Logar', 'Lōgar', 'Wilāyat-e Lōgar', 'Lōgar', 1, NOW(6), NOW(6), 1, 1),
(1135022, 1, 'AF-LAG', NULL, NULL, '0', 'AF-LAG', 'AF-LAG', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Laghmān', 'Laghman', 'Laghmān', 'Wilāyat-e Laghmān', 'Laghmān', 1, NOW(6), NOW(6), 1, 1),
(1135690, 1, 'AF-KDZ', NULL, NULL, '0', 'AF-KDZ', 'AF-KDZ', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Kunduz', 'Kunduz', 'Kunduz', 'Kunduz', 'Kunduz', 1, NOW(6), NOW(6), 1, 1),
(1135702, 1, 'AF-KNR', NULL, NULL, '0', 'AF-KNR', 'AF-KNR', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Kunaṟ', 'Kunar', 'Kunaṟ', 'Wilāyat-e Kunaṟ', 'Kunaṟ', 1, NOW(6), NOW(6), 1, 1),
(1138255, 1, 'AF-KAP', NULL, NULL, '0', 'AF-KAP', 'AF-KAP', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Kāpīsā', 'Kapisa', 'Kāpīsā', 'Wilāyat-e Kāpīsā', 'Kāpīsā', 1, NOW(6), NOW(6), 1, 1),
(1138335, 1, 'AF-KAN', NULL, NULL, '0', 'AF-KAN', 'AF-KAN', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Kandahār', 'Kandahar', 'Kandahār', 'Kandahār', 'Kandahār', 1, NOW(6), NOW(6), 1, 1),
(1138957, 1, 'AF-KAB', NULL, NULL, '0', 'AF-KAB', 'AF-KAB', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Kābul', 'Kabul', 'Kābul', 'Wilāyat-e Kābul', 'Kābul', 1, NOW(6), NOW(6), 1, 1),
(1139049, 1, 'AF-JOW', NULL, NULL, '0', 'AF-JOW', 'AF-JOW', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Jowzjān', 'Jowzjan', 'Jowzjān', 'Wilāyat-e Jowzjān', 'Jowzjān', 1, NOW(6), NOW(6), 1, 1),
(1140025, 1, 'AF-HER', NULL, NULL, '0', 'AF-HER', 'AF-HER', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Herāt', 'Herat', 'Herāt', 'Herāt', 'Herāt', 1, NOW(6), NOW(6), 1, 1),
(1140043, 1, 'AF-HEL', NULL, NULL, '0', 'AF-HEL', 'AF-HEL', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Helmand', 'Helmand', 'Helmand', 'Helmand', 'Helmand', 1, NOW(6), NOW(6), 1, 1),
(1141103, 1, 'AF-GHO', NULL, NULL, '0', 'AF-GHO', 'AF-GHO', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Ghōr', 'Ghor', 'Ghōr', 'Wilāyat-e Ghōr', 'Ghōr', 1, NOW(6), NOW(6), 1, 1),
(1141268, 1, 'AF-GHA', NULL, NULL, '0', 'AF-GHA', 'AF-GHA', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Ghaznī', 'Ghazni', 'Ghaznī', 'Wilāyat-e Ghaznī', 'Ghaznī', 1, NOW(6), NOW(6), 1, 1),
(1142226, 1, 'AF-FYB', NULL, NULL, '0', 'AF-FYB', 'AF-FYB', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Fāryāb', 'Faryab', 'Fāryāb', 'Faryab Province', 'Fāryāb', 1, NOW(6), NOW(6), 1, 1),
(1142263, 1, 'AF-FRA', NULL, NULL, '0', 'AF-FRA', 'AF-FRA', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Farāh', 'Farah', 'Farāh', 'Farāh', 'Farāh', 1, NOW(6), NOW(6), 1, 1),
(1147239, 1, 'AF-BAM', NULL, NULL, '0', 'AF-BAM', 'AF-BAM', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Bāmyān', 'Bamyan', 'Bāmyān', 'Wilāyat-e Bāmyān', 'Bāmyān', 1, NOW(6), NOW(6), 1, 1),
(1147288, 1, 'AF-BAL', NULL, NULL, '0', 'AF-BAL', 'AF-BAL', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Balkh', 'Balkh', 'Balkh', 'Balkh', 'Balkh', 1, NOW(6), NOW(6), 1, 1),
(1147537, 1, 'AF-BGL', NULL, NULL, '0', 'AF-BGL', 'AF-BGL', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Baghlān', 'Baghlan', 'Baghlān', 'Wilāyat-e Baghlān', 'Baghlān', 1, NOW(6), NOW(6), 1, 1),
(1147707, 1, 'AF-BDG', NULL, NULL, '0', 'AF-BDG', 'AF-BDG', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Bādghīs', 'Badghis', 'Bādghīs', 'Bādghīs', 'Bādghīs', 1, NOW(6), NOW(6), 1, 1),
(1147745, 1, 'AF-BDS', NULL, NULL, '0', 'AF-BDS', 'AF-BDS', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Badakhshān', 'Badakhshan', 'Badakhshān', 'Badakhshān', 'Badakhshān', 1, NOW(6), NOW(6), 1, 1),
(1444362, 1, 'AF-KHO', NULL, NULL, '0', 'AF-KHO', 'AF-KHO', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Khowst', 'Khost', 'Khowst', 'Velāyat-e Khowst', 'Khowst', 1, NOW(6), NOW(6), 1, 1),
(1444363, 1, 'AF-NUR', NULL, NULL, '0', 'AF-NUR', 'AF-NUR', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Nūrestān', 'Nurestan', 'Nūrestān', 'Velāyat-e Nūrestān', 'Nūrestān', 1, NOW(6), NOW(6), 1, 1),
(6957553, 1, 'AF-DAY', NULL, NULL, '0', 'AF-DAY', 'AF-DAY', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Daykundi', 'Daykundi', 'Daykundi', 'Daykundi Province', 'Daykundi', 1, NOW(6), NOW(6), 1, 1),
(6957555, 1, 'AF-PAN', NULL, NULL, '0', 'AF-PAN', 'AF-PAN', '+93', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_af' AND id_country = 1),
    'Panjshir', 'Panjshir', 'Panjshir', 'Panjshir', 'Panjshir', 1, NOW(6), NOW(6), 1, 1);