-- Insertar tipo de división geográfica ADM1 para ANGUILLA: Distrito
INSERT INTO `t075t_division_types` (
    `code`, `id_country`, `id_level_type`, `name_spanish`, `name_english`, 
    `name_iso`, `name_original`, `name_transcribed`, `status`, 
    `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES (
    'distrito_ai', 8, 8, 'Distrito', 'District', 
    'District', 'District', 'Distrito', 1, NOW(6), NOW(6), 1, 1
);

-- Insertar las divisiones ADM1 de ANGUILLA (Distritos)
INSERT INTO `t076t_states` (
    `geo_id`, `id_country`, `code`, `code_dane`, `code_dian`, `code_iso_numeric`, 
    `code_iso_alpha2`, `code_iso_alpha3`, `phone_code`, `id_division_type`, 
    `name_spanish`, `name_english`, `name_iso`, `name_original`, `name_transcribed`, 
    `status`, `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES 
(11205389, 8, 'AI-BP', NULL, NULL, '0', 'AI-BP', 'AI-BP', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'Blowing Point', 'Blowing Point', 'Blowing Point', 'Blowing Point', 
    'Blowing Point', 1, NOW(6), NOW(6), 1, 1),
(11205392, 8, 'AI-SG', NULL, NULL, '0', 'AI-SG', 'AI-SG', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'Sandy Ground', 'Sandy Ground', 'Sandy Ground', 'Sandy Ground', 
    'Sandy Ground', 1, NOW(6), NOW(6), 1, 1),
(11205393, 8, 'AI-SH', NULL, NULL, '0', 'AI-SH', 'AI-SH', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'Sandy Hill', 'Sandy Hill', 'Sandy Hill', 'Sandy Hill', 
    'Sandy Hill', 1, NOW(6), NOW(6), 1, 1),
(11205396, 8, 'AI-TV', NULL, NULL, '0', 'AI-TV', 'AI-TV', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'The Valley', 'The Valley', 'The Valley', 'The Valley', 
    'The Valley', 1, NOW(6), NOW(6), 1, 1),
(11205433, 8, 'AI-EE', NULL, NULL, '0', 'AI-EE', 'AI-EE', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'East End', 'East End', 'East End', 'East End', 
    'East End', 1, NOW(6), NOW(6), 1, 1),
(11205436, 8, 'AI-NH', NULL, NULL, '0', 'AI-NH', 'AI-NH', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'North Hill', 'North Hill', 'North Hill', 'North Hill', 
    'North Hill', 1, NOW(6), NOW(6), 1, 1),
(11205437, 8, 'AI-WE', NULL, NULL, '0', 'AI-WE', 'AI-WE', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'West End', 'West End', 'West End', 'West End', 
    'West End', 1, NOW(6), NOW(6), 1, 1),
(11205438, 8, 'AI-SH', NULL, NULL, '0', 'AI-SH', 'AI-SH', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'South Hill', 'South Hill', 'South Hill', 'South Hill', 
    'South Hill', 1, NOW(6), NOW(6), 1, 1),
(11205439, 8, 'AI-TQ', NULL, NULL, '0', 'AI-TQ', 'AI-TQ', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'The Quarter', 'The Quarter', 'The Quarter', 'The Quarter', 
    'The Quarter', 1, NOW(6), NOW(6), 1, 1),
(11205440, 8, 'AI-NS', NULL, NULL, '0', 'AI-NS', 'AI-NS', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'North Side', 'North Side', 'North Side', 'North Side', 
    'North Side', 1, NOW(6), NOW(6), 1, 1),
(11205441, 8, 'AI-IH', NULL, NULL, '0', 'AI-IH', 'AI-IH', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'Island Harbour', 'Island Harbour', 'Island Harbour', 'Island Harbour', 
    'Island Harbour', 1, NOW(6), NOW(6), 1, 1),
(11205442, 8, 'AI-GH', NULL, NULL, '0', 'AI-GH', 'AI-GH', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'George Hill', 'George Hill', 'George Hill', 'George Hill', 
    'George Hill', 1, NOW(6), NOW(6), 1, 1),
(11205443, 8, 'AI-ST', NULL, NULL, '0', 'AI-ST', 'AI-ST', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'Stoney Ground', 'Stoney Ground', 'Stoney Ground', 'Stoney Ground', 
    'Stoney Ground', 1, NOW(6), NOW(6), 1, 1),
(11205444, 8, 'AI-TF', NULL, NULL, '0', 'AI-TF', 'AI-TF', '+1-264', 
    (SELECT id FROM t075t_division_types WHERE code = 'distrito_ai' AND id_country = 8),
    'The Farrington', 'The Farrington', 'The Farrington', 'The Farrington', 
    'The Farrington', 1, NOW(6), NOW(6), 1, 1);