-- Insertar tipo de división geográfica ADM1 para ANGOLA: Provincia
INSERT INTO `t075t_division_types` (
    `code`, `id_country`, `id_level_type`, `name_spanish`, `name_english`, 
    `name_iso`, `name_original`, `name_transcribed`, `status`, 
    `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES (
    'provincia_ao', 7, 8, 'Provincia', 'Province', 
    'Província', 'Província', 'Provincia', 1, NOW(6), NOW(6), 1, 1
);

-- Insertar las divisiones ADM1 de ANGOLA (Provincias)
INSERT INTO `t076t_states` (
    `geo_id`, `id_country`, `code`, `code_dane`, `code_dian`, `code_iso_numeric`, 
    `code_iso_alpha2`, `code_iso_alpha3`, `phone_code`, `id_division_type`, 
    `name_spanish`, `name_english`, `name_iso`, `name_original`, `name_transcribed`, 
    `status`, `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES 
(145701, 7, 'AO-LSU', NULL, NULL, '0', 'AO-LSU', 'AO-LSU', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Lunda Sul', 'Lunda Sul', 'Lunda Sul', 'Lunda-Sul', 
    'Lunda Sul', 1, NOW(6), NOW(6), 1, 1),
(145702, 7, 'AO-LNO', NULL, NULL, '0', 'AO-LNO', 'AO-LNO', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Lunda Norte', 'Lunda Norte', 'Lunda Norte', 'Lunda Norte Province', 
    'Lunda Norte', 1, NOW(6), NOW(6), 1, 1),
(875996, 7, 'AO-MOX', NULL, NULL, '0', 'AO-MOX', 'AO-MOX', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Moxico', 'Moxico', 'Moxico', 'Moxico', 
    'Moxico', 1, NOW(6), NOW(6), 1, 1),
(876337, 7, 'AO-CCU', NULL, NULL, '0', 'AO-CCU', 'AO-CCU', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Cuando Cubango', 'Cuando Cubango', 'Cuando Cubango', 'Cuando Cubango', 
    'Cuando Cubango', 1, NOW(6), NOW(6), 1, 1),
(2236355, 7, 'AO-ZAI', NULL, NULL, '0', 'AO-ZAI', 'AO-ZAI', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Zaire', 'Zaire', 'Zaire', 'Zaire', 
    'Zaire', 1, NOW(6), NOW(6), 1, 1),
(2236566, 7, 'AO-UIG', NULL, NULL, '0', 'AO-UIG', 'AO-UIG', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Uíge', 'Uíge', 'Uíge', 'Província do Uíge', 
    'Uíge', 1, NOW(6), NOW(6), 1, 1),
(2239858, 7, 'AO-MAL', NULL, NULL, '0', 'AO-MAL', 'AO-MAL', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Malanje', 'Malanje', 'Malanje', 'Malanje Province', 
    'Malanje', 1, NOW(6), NOW(6), 1, 1),
(2240444, 7, 'AO-LUA', NULL, NULL, '0', 'AO-LUA', 'AO-LUA', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Luanda', 'Luanda', 'Luanda', 'Luanda Province', 
    'Luanda', 1, NOW(6), NOW(6), 1, 1),
(2241660, 7, 'AO-CNO', NULL, NULL, '0', 'AO-CNO', 'AO-CNO', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Cuanza Norte', 'Cuanza Norte', 'Cuanza Norte', 'Cuanza Norte Province', 
    'Cuanza Norte', 1, NOW(6), NOW(6), 1, 1),
(2243266, 7, 'AO-CAB', NULL, NULL, '0', 'AO-CAB', 'AO-CAB', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Cabinda', 'Cabinda', 'Cabinda', 'Cabinda', 
    'Cabinda', 1, NOW(6), NOW(6), 1, 1),
(2243598, 7, 'AO-BGO', NULL, NULL, '0', 'AO-BGO', 'AO-BGO', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Bengo', 'Bengo', 'Bengo', 'Bengo Province', 
    'Bengo', 1, NOW(6), NOW(6), 1, 1),
(3347016, 7, 'AO-NAM', NULL, NULL, '0', 'AO-NAM', 'AO-NAM', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Namibe', 'Namibe', 'Namibe', 'Namibe Province', 
    'Namibe', 1, NOW(6), NOW(6), 1, 1),
(3348303, 7, 'AO-HUI', NULL, NULL, '0', 'AO-HUI', 'AO-HUI', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Huíla', 'Huíla', 'Huíla', 'Huila Province', 
    'Huíla', 1, NOW(6), NOW(6), 1, 1),
(3348310, 7, 'AO-HUA', NULL, NULL, '0', 'AO-HUA', 'AO-HUA', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Huambo', 'Huambo', 'Huambo', 'Huambo', 
    'Huambo', 1, NOW(6), NOW(6), 1, 1),
(3349096, 7, 'AO-CNN', NULL, NULL, '0', 'AO-CNN', 'AO-CNN', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Cunene', 'Cunene', 'Cunene', 'Cunene Province', 
    'Cunene', 1, NOW(6), NOW(6), 1, 1),
(3349234, 7, 'AO-CSU', NULL, NULL, '0', 'AO-CSU', 'AO-CSU', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Cuanza Sul', 'Cuanza Sul', 'Cuanza Sul', 'Cuanza-Sul', 
    'Cuanza Sul', 1, NOW(6), NOW(6), 1, 1),
(3351640, 7, 'AO-BIE', NULL, NULL, '0', 'AO-BIE', 'AO-BIE', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Bié', 'Bié', 'Bié', 'Província do Bié', 
    'Bié', 1, NOW(6), NOW(6), 1, 1),
(3351660, 7, 'AO-BGU', NULL, NULL, '0', 'AO-BGU', 'AO-BGU', '+244', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ao' AND id_country = 7),
    'Benguela', 'Benguela', 'Benguela', 'Benguela', 
    'Benguela', 1, NOW(6), NOW(6), 1, 1);