-- Insertar tipo de división geográfica ADM1 para ARGENTINA: Provincia
INSERT INTO `t075t_division_types` (
    `code`, `id_country`, `id_level_type`, `name_spanish`, `name_english`, 
    `name_iso`, `name_original`, `name_transcribed`, `status`, 
    `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES (
    'provincia_ar', 11, 8, 'Provincia', 'Province', 
    'Provincia', 'Provincia', 'Provincia', 1, NOW(6), NOW(6), 1, 1
);

-- Insertar las divisiones ADM1 de ARGENTINA (Provincias y Ciudad Autónoma de Buenos Aires)
INSERT INTO `t076t_states` (
    `geo_id`, `id_country`, `code`, `code_dane`, `code_dian`, `code_iso_numeric`, 
    `code_iso_alpha2`, `code_iso_alpha3`, `phone_code`, `id_division_type`, 
    `name_spanish`, `name_english`, `name_iso`, `name_original`, `name_transcribed`, 
    `status`, `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES 
(3430657, 11, 'AR-N', NULL, NULL, '0', 'AR-N', 'AR-N', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Misiones', 'Misiones', 'Misiones', 'Misiones Province', 
    'Misiones', 1, NOW(6), NOW(6), 1, 1),
(3433896, 11, 'AR-P', NULL, NULL, '0', 'AR-P', 'AR-P', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Formosa', 'Formosa', 'Formosa', 'Formosa Province', 
    'Formosa', 1, NOW(6), NOW(6), 1, 1),
(3433955, 11, 'AR-C', NULL, NULL, '0', 'AR-C', 'AR-C', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Ciudad Autónoma de Buenos Aires', 'Autonomous City of Buenos Aires', 'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 
    'Ciudad Autónoma de Buenos Aires', 1, NOW(6), NOW(6), 1, 1),
(3434137, 11, 'AR-E', NULL, NULL, '0', 'AR-E', 'AR-E', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Entre Ríos', 'Entre Ríos', 'Entre Ríos', 'Entre Ríos Province', 
    'Entre Ríos', 1, NOW(6), NOW(6), 1, 1),
(3435214, 11, 'AR-W', NULL, NULL, '0', 'AR-W', 'AR-W', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Corrientes', 'Corrientes', 'Corrientes', 'Corrientes Province', 
    'Corrientes', 1, NOW(6), NOW(6), 1, 1),
(3435907, 11, 'AR-B', NULL, NULL, '0', 'AR-B', 'AR-B', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Buenos Aires', 'Buenos Aires', 'Buenos Aires', 'Buenos Aires', 
    'Buenos Aires', 1, NOW(6), NOW(6), 1, 1),
(3833578, 11, 'AR-T', NULL, NULL, '0', 'AR-T', 'AR-T', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Tucumán', 'Tucumán', 'Tucumán', 'Tucumán Province', 
    'Tucumán', 1, NOW(6), NOW(6), 1, 1),
(3834450, 11, 'AR-V', NULL, NULL, '0', 'AR-V', 'AR-V', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Tierra del Fuego', 'Tierra del Fuego', 'Tierra del Fuego', 'Tierra del Fuego Province', 
    'Tierra del Fuego', 1, NOW(6), NOW(6), 1, 1),
(3835868, 11, 'AR-G', NULL, NULL, '0', 'AR-G', 'AR-G', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Santiago del Estero', 'Santiago del Estero', 'Santiago del Estero', 'Santiago del Estero Province', 
    'Santiago del Estero', 1, NOW(6), NOW(6), 1, 1),
(3836276, 11, 'AR-S', NULL, NULL, '0', 'AR-S', 'AR-S', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Santa Fe', 'Santa Fe', 'Santa Fe', 'Santa Fe Province', 
    'Santa Fe', 1, NOW(6), NOW(6), 1, 1),
(3836350, 11, 'AR-Z', NULL, NULL, '0', 'AR-Z', 'AR-Z', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Santa Cruz', 'Santa Cruz', 'Santa Cruz', 'Santa Cruz Province', 
    'Santa Cruz', 1, NOW(6), NOW(6), 1, 1),
(3837029, 11, 'AR-D', NULL, NULL, '0', 'AR-D', 'AR-D', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'San Luis', 'San Luis', 'San Luis', 'San Luis Province', 
    'San Luis', 1, NOW(6), NOW(6), 1, 1),
(3837152, 11, 'AR-J', NULL, NULL, '0', 'AR-J', 'AR-J', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'San Juan', 'San Juan', 'San Juan', 'San Juan Province', 
    'San Juan', 1, NOW(6), NOW(6), 1, 1),
(3838231, 11, 'AR-A', NULL, NULL, '0', 'AR-A', 'AR-A', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Salta', 'Salta', 'Salta', 'Salta Province', 
    'Salta', 1, NOW(6), NOW(6), 1, 1),
(3838830, 11, 'AR-R', NULL, NULL, '0', 'AR-R', 'AR-R', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Río Negro', 'Río Negro', 'Río Negro', 'Río Negro Province', 
    'Río Negro', 1, NOW(6), NOW(6), 1, 1),
(3843122, 11, 'AR-Q', NULL, NULL, '0', 'AR-Q', 'AR-Q', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Neuquén', 'Neuquén', 'Neuquén', 'Neuquén Province', 
    'Neuquén', 1, NOW(6), NOW(6), 1, 1),
(3844419, 11, 'AR-M', NULL, NULL, '0', 'AR-M', 'AR-M', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Mendoza', 'Mendoza', 'Mendoza', 'Mendoza Province', 
    'Mendoza', 1, NOW(6), NOW(6), 1, 1),
(3848949, 11, 'AR-F', NULL, NULL, '0', 'AR-F', 'AR-F', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'La Rioja', 'La Rioja', 'La Rioja', 'La Rioja Province', 
    'La Rioja', 1, NOW(6), NOW(6), 1, 1),
(3849574, 11, 'AR-L', NULL, NULL, '0', 'AR-L', 'AR-L', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'La Pampa', 'La Pampa', 'La Pampa', 'La Pampa Province', 
    'La Pampa', 1, NOW(6), NOW(6), 1, 1),
(3853404, 11, 'AR-Y', NULL, NULL, '0', 'AR-Y', 'AR-Y', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Jujuy', 'Jujuy', 'Jujuy', 'Jujuy Province', 
    'Jujuy', 1, NOW(6), NOW(6), 1, 1),
(3860255, 11, 'AR-X', NULL, NULL, '0', 'AR-X', 'AR-X', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Córdoba', 'Córdoba', 'Córdoba', 'Córdoba Province', 
    'Córdoba', 1, NOW(6), NOW(6), 1, 1),
(3861244, 11, 'AR-U', NULL, NULL, '0', 'AR-U', 'AR-U', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Chubut', 'Chubut', 'Chubut', 'Chubut Province', 
    'Chubut', 1, NOW(6), NOW(6), 1, 1),
(3861887, 11, 'AR-H', NULL, NULL, '0', 'AR-H', 'AR-H', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Chaco', 'Chaco', 'Chaco', 'Chaco Province', 
    'Chaco', 1, NOW(6), NOW(6), 1, 1),
(3862286, 11, 'AR-K', NULL, NULL, '0', 'AR-K', 'AR-K', '+54', 
    (SELECT id FROM t075t_division_types WHERE code = 'provincia_ar' AND id_country = 11),
    'Catamarca', 'Catamarca', 'Catamarca', 'Catamarca Province', 
    'Catamarca', 1, NOW(6), NOW(6), 1, 1);