-- Insertar tipo de división geográfica ADM1 para INDONESIA: Provincia
INSERT INTO `t075t_division_types` (
    `code`, `id_country`, `id_level_type`, `name_spanish`, `name_english`, 
    `name_iso`, `name_original`, `name_transcribed`, `status`, 
    `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES (
    'provincia_id', 103, 8, 'Provincia', 'Province', 
    'Provinsi', 'Provinsi', 'provinsi', 1, NOW(6), NOW(6), 1, 1
);

-- Insertar las divisiones ADM1 de INDONESIA (Provincias)
INSERT INTO `t076t_states` (
    `geo_id`, `id_country`, `code`, `code_dane`, `code_dian`, `code_iso_numeric`, 
    `code_iso_alpha2`, `code_iso_alpha3`, `phone_code`, `id_division_type`, 
    `name_spanish`, `name_english`, `name_iso`, `name_original`, `name_transcribed`, 
    `status`, `created_at`, `updated_at`, `created_by`, `updated_by`
) VALUES 
    (1213642, 103, 'ID-SU', NULL, NULL, '26', 'ID-SU', 'ID-SU', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sumatra Utara', 'North Sumatra', 'Sumatera Utara', 'North Sumatra', 'North Sumatra', 1, NOW(6), NOW(6), 1, 1),
    (1215638, 103, 'ID-AC', NULL, NULL, '01', 'ID-AC', 'ID-AC', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Aceh', 'Aceh', 'Aceh', 'Nanggroe Aceh Darussalam Province', 'Nanggroe Aceh Darussalam Province', 1, NOW(6), NOW(6), 1, 1),
    (1621176, 103, 'ID-YO', NULL, NULL, '10', 'ID-YO', 'ID-YO', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Yogyakarta', 'Yogyakarta', 'Yogyakarta', 'Daerah Istimewa Yogyakarta', 'Daerah Istimewa Yogyakarta', 1, NOW(6), NOW(6), 1, 1),
    (1626196, 103, 'ID-SS', NULL, NULL, '32', 'ID-SS', 'ID-SS', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sumatra Selatan', 'South Sumatra', 'Sumatera Selatan', 'Sumatera Selatan', 'Sumatera Selatan', 1, NOW(6), NOW(6), 1, 1),
    (1626197, 103, 'ID-SB', NULL, NULL, '24', 'ID-SB', 'ID-SB', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sumatra Barat', 'West Sumatra', 'Sumatera Barat', 'Provinsi Sumatera Barat', 'Provinsi Sumatera Barat', 1, NOW(6), NOW(6), 1, 1),
    (1626229, 103, 'ID-SA', NULL, NULL, '31', 'ID-SA', 'ID-SA', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sulawesi Utara', 'North Sulawesi', 'Sulawesi Utara', 'Sulawesi Utara', 'Sulawesi Utara', 1, NOW(6), NOW(6), 1, 1),
    (1626230, 103, 'ID-SG', NULL, NULL, '22', 'ID-SG', 'ID-SG', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sulawesi Tenggara', 'Southeast Sulawesi', 'Sulawesi Tenggara', 'Sulawesi Tenggara', 'Sulawesi Tenggara', 1, NOW(6), NOW(6), 1, 1),
    (1626231, 103, 'ID-ST', NULL, NULL, '21', 'ID-ST', 'ID-ST', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sulawesi Tengah', 'Central Sulawesi', 'Sulawesi Tengah', 'Sulawesi Tengah', 'Sulawesi Tengah', 1, NOW(6), NOW(6), 1, 1),
    (1626232, 103, 'ID-SN', NULL, NULL, '38', 'ID-SN', 'ID-SN', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sulawesi Selatan', 'South Sulawesi', 'Sulawesi Selatan', 'Provinsi Sulawesi Selatan', 'Provinsi Sulawesi Selatan', 1, NOW(6), NOW(6), 1, 1),
    (1629652, 103, 'ID-RI', NULL, NULL, '37', 'ID-RI', 'ID-RI', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Riau', 'Riau', 'Riau', 'Provinsi Riau', 'Provinsi Riau', 1, NOW(6), NOW(6), 1, 1),
    (1633791, 103, 'ID-NT', NULL, NULL, '18', 'ID-NT', 'ID-NT', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Nusa Tenggara Timur', 'East Nusa Tenggara', 'Nusa Tenggara Timur', 'East Nusa Tenggara', 'East Nusa Tenggara', 1, NOW(6), NOW(6), 1, 1),
    (1633792, 103, 'ID-NB', NULL, NULL, '17', 'ID-NB', 'ID-NB', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Nusa Tenggara Barat', 'West Nusa Tenggara', 'Nusa Tenggara Barat', 'West Nusa Tenggara', 'West Nusa Tenggara', 1, NOW(6), NOW(6), 1, 1),
    (1636627, 103, 'ID-MA', NULL, NULL, '28', 'ID-MA', 'ID-MA', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Maluku', 'Maluku', 'Maluku', 'Provinsi Maluku', 'Provinsi Maluku', 1, NOW(6), NOW(6), 1, 1),
    (1638535, 103, 'ID-LA', NULL, NULL, '15', 'ID-LA', 'ID-LA', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Lampung', 'Lampung', 'Lampung', 'Provinsi Lampung', 'Provinsi Lampung', 1, NOW(6), NOW(6), 1, 1),
    (1641897, 103, 'ID-KI', NULL, NULL, '14', 'ID-KI', 'ID-KI', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Kalimantan Timur', 'East Kalimantan', 'Kalimantan Timur', 'Provinsi Kalimantan Timur', 'Provinsi Kalimantan Timur', 1, NOW(6), NOW(6), 1, 1),
    (1641898, 103, 'ID-KT', NULL, NULL, '13', 'ID-KT', 'ID-KT', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Kalimantan Tengah', 'Central Kalimantan', 'Kalimantan Tengah', 'Provinsi Kalimantan Tengah', 'Provinsi Kalimantan Tengah', 1, NOW(6), NOW(6), 1, 1),
    (1641899, 103, 'ID-KS', NULL, NULL, '12', 'ID-KS', 'ID-KS', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Kalimantan Selatan', 'South Kalimantan', 'Kalimantan Selatan', 'Provinsi Kalimantan Selatan', 'Provinsi Kalimantan Selatan', 1, NOW(6), NOW(6), 1, 1),
    (1641900, 103, 'ID-KB', NULL, NULL, '11', 'ID-KB', 'ID-KB', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Kalimantan Barat', 'West Kalimantan', 'Kalimantan Barat', 'Provinsi Kalimantan Barat', 'Provinsi Kalimantan Barat', 1, NOW(6), NOW(6), 1, 1),
    (1642668, 103, 'ID-JI', NULL, NULL, '08', 'ID-JI', 'ID-JI', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Jawa Timur', 'East Java', 'Jawa Timur', 'Jawa Timur', 'Jawa Timur', 1, NOW(6), NOW(6), 1, 1),
    (1642669, 103, 'ID-JT', NULL, NULL, '07', 'ID-JT', 'ID-JT', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Jawa Tengah', 'Central Java', 'Jawa Tengah', 'Provinsi Jawa Tengah', 'Provinsi Jawa Tengah', 1, NOW(6), NOW(6), 1, 1),
    (1642672, 103, 'ID-JB', NULL, NULL, '30', 'ID-JB', 'ID-JB', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Jawa Barat', 'West Java', 'Jawa Barat', 'Jawa Barat', 'Jawa Barat', 1, NOW(6), NOW(6), 1, 1),
    (1642856, 103, 'ID-JA', NULL, NULL, '05', 'ID-JA', 'ID-JA', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Jambi', 'Jambi', 'Jambi', 'Provinsi Jambi', 'Provinsi Jambi', 1, NOW(6), NOW(6), 1, 1),
    (1642907, 103, 'ID-JK', NULL, NULL, '04', 'ID-JK', 'ID-JK', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Yakarta', 'Jakarta', 'Jakarta', 'Daerah Khusus Ibukota Jakarta', 'Daerah Khusus Ibukota Jakarta', 1, NOW(6), NOW(6), 1, 1),
    (1643012, 103, 'ID-PA', NULL, NULL, '36', 'ID-PA', 'ID-PA', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Papua', 'Papua', 'Papua', 'Provinsi Papua', 'Provinsi Papua', 1, NOW(6), NOW(6), 1, 1),
    (1649147, 103, 'ID-BE', NULL, NULL, '03', 'ID-BE', 'ID-BE', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Bengkulu', 'Bengkulu', 'Bengkulu', 'Propinsi Bengkulu', 'Propinsi Bengkulu', 1, NOW(6), NOW(6), 1, 1),
    (1650535, 103, 'ID-BA', NULL, NULL, '02', 'ID-BA', 'ID-BA', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Bali', 'Bali', 'Bali', 'Provinsi Bali', 'Provinsi Bali', 1, NOW(6), NOW(6), 1, 1),
    (1923045, 103, 'ID-BT', NULL, NULL, '33', 'ID-BT', 'ID-BT', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Banten', 'Banten', 'Banten', 'Banten', 'Banten', 1, NOW(6), NOW(6), 1, 1),
    (1923046, 103, 'ID-GO', NULL, NULL, '34', 'ID-GO', 'ID-GO', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Gorontalo', 'Gorontalo', 'Gorontalo', 'Provinsi Gorontalo', 'Provinsi Gorontalo', 1, NOW(6), NOW(6), 1, 1),
    (1923047, 103, 'ID-BB', NULL, NULL, '35', 'ID-BB', 'ID-BB', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Bangka Belitung', 'Bangka Belitung', 'Bangka Belitung', 'Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung', 1, NOW(6), NOW(6), 1, 1),
    (1958070, 103, 'ID-MU', NULL, NULL, '29', 'ID-MU', 'ID-MU', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Maluku Utara', 'North Maluku', 'Maluku Utara', 'North Maluku', 'North Maluku', 1, NOW(6), NOW(6), 1, 1),
    (1996549, 103, 'ID-PB', NULL, NULL, '39', 'ID-PB', 'ID-PB', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Papua Barat', 'West Papua', 'Papua Barat', 'Provinsi Papua Barat', 'Provinsi Papua Barat', 1, NOW(6), NOW(6), 1, 1),
    (1996550, 103, 'ID-SR', NULL, NULL, '41', 'ID-SR', 'ID-SR', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Sulawesi Barat', 'West Sulawesi', 'Sulawesi Barat', 'Provinsi Sulawesi Barat', 'Provinsi Sulawesi Barat', 1, NOW(6), NOW(6), 1, 1),
    (1996551, 103, 'ID-KR', NULL, NULL, '40', 'ID-KR', 'ID-KR', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Kepulauan Riau', 'Riau Islands', 'Kepulauan Riau', 'Provinsi Kepulauan Riau', 'Provinsi Kepulauan Riau', 1, NOW(6), NOW(6), 1, 1),
    (8604684, 103, 'ID-KU', NULL, NULL, '42', 'ID-KU', 'ID-KU', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Kalimantan Utara', 'North Kalimantan', 'Kalimantan Utara', 'North Kalimantan', 'North Kalimantan', 1, NOW(6), NOW(6), 1, 1),
    (12503510, 103, 'ID-PD', NULL, NULL, 'PD', 'ID-PD', 'ID-PD', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Papua Barat Daya', 'Southwest Papua', 'Papua Barat Daya', 'Southwest Papua', 'Southwest Papua', 1, NOW(6), NOW(6), 1, 1),
    (12503511, 103, 'ID-PT', NULL, NULL, 'PT', 'ID-PT', 'ID-PT', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Papua Tengah', 'Central Papua', 'Papua Tengah', 'Central Papua', 'Central Papua', 1, NOW(6), NOW(6), 1, 1),
    (12503512, 103, 'ID-PE', NULL, NULL, 'PE', 'ID-PE', 'ID-PE', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Papua Pegunungan', 'Highland Papua', 'Papua Pegunungan', 'Highland Papua', 'Highland Papua', 1, NOW(6), NOW(6), 1, 1),
    (12503513, 103, 'ID-PS', NULL, NULL, 'PS', 'ID-PS', 'ID-PS', '+62', (SELECT id FROM t075t_division_types WHERE code = 'provincia_id' AND id_country = 103), 'Papua Selatan', 'South Papua', 'Papua Selatan', 'South Papua', 'South Papua', 1, NOW(6), NOW(6), 1, 1);